#!/bin/sh

num_files=$1
help_file="win-config.html"
file_prefix="win-config-"
suffix="html"
counter=0;

while let "counter < $num_files"; do
	current_url=$help_file\#WIN-CONFIG-$counter
	current_file=$file_prefix$counter.$suffix
	
	echo Create redirect file: $current_file

	echo \<html\> > $current_file
	echo \<head\> >> $current_file
	echo \<title\>redirect\<\/title\> >> $current_file
	echo \<meta http-equiv=\"refresh\" content=\"0\; \
		url=$current_url\"\> >> $current_file
	echo \<\/head\> >> $current_file
	echo \<body\>\<\/body\> >> $current_file
	echo \<\/html\> >> $current_file

	let "counter += 1"
done

