/* Automatically generated by po2tbl.sed from balsa.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Send", 2},
  {"Attach File", 3},
  {"Close", 4},
  {"Message", 5},
  {"Cut", 6},
  {"Copy", 7},
  {"Paste", 8},
  {"Edit", 9},
  {"Contents", 10},
  {"Help", 11},
  {"File", 12},
  {"Get New Mail", 13},
  {"Exit", 14},
  {"New", 15},
  {"Reply", 16},
  {"Foward", 17},
  {"Delete", 18},
  {"Undelete", 19},
  {"Preferences...", 20},
  {"Mailbox Manager...", 21},
  {"Settings", 22},
  {"Toolbar", 23},
  {"Icons", 24},
  {"Text", 25},
  {"Both", 26},
  {"View", 27},
  {"About", 28},
};

int _msg_tbl_length = 28;
