/* Automatically generated by po2tbl.sed from balsa.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Send", 2},
  {"Attach File", 3},
  {"Close", 4},
  {"Message", 5},
  {"Cut", 6},
  {"Copy", 7},
  {"Paste", 8},
  {"Edit", 9},
  {"Contents", 10},
  {"Help", 11},
  {"File", 12},
  {"Mailboxes/<Separator>", 13},
  {"Get New Mail", 14},
  {"Check POP3", 15},
  {"Exit", 16},
  {"New", 17},
  {"Reply", 18},
  {"Forward", 19},
  {"Delete", 20},
  {"Undelete", 21},
  {"MDI", 22},
  {"Mailbox List", 23},
  {"Mailboxes", 24},
  {"Preferences...", 25},
  {"Mailbox Manager...", 26},
  {"Settings", 27},
  {"About", 28},
};

int _msg_tbl_length = 28;
