/* Automatically generated by po2tbl.sed from balsa.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"From", 2},
  {"Subject", 3},
  {"Date", 4},
  {"Welcome To Balsa!", 5},
  {"Previous...", 6},
  {"Next...", 7},
  {"\
Welcome to Balsa!\n\
\n", 8},
  {"You seem to be running Balsa for the first time.\n", 9},
  {"The following steps will setup Balsa by asking a few simple questions.", 10},
  {"\
Once you have completed these steps, you can always change them at a later \
time through Balsa's preferences.", 11},
  {"\
Please check the about box in Balsa's main window for more information on \
contacting the authors or reporting bugs.", 12},
  {"\
Welcome to Balsa!  The following steps will help you get setup to use Balsa.", 13},
  {"Your name:", 14},
  {"E-Mail address:", 15},
  {"SMTP server:", 16},
  {"Inbox Path:", 17},
  {"Outbox Path:", 18},
  {"Trash Path:", 19},
  {"\
If you wish to use IMAP for these\n\
please change them inside Balsa\n", 20},
  {"Balsa is now ready to run.  Click finish to save your settings", 21},
  {"Finish", 22},
  {"Unable to Open Mailbox!", 23},
  {"Transfer", 24},
  {"Change Status", 25},
  {"Unread", 26},
  {"Read", 27},
  {"Replied", 28},
  {"Forwarded", 29},
  {"Undelete", 30},
  {"Delete", 31},
  {"Local Mailbox Loaded as: %s\n", 32},
  {"Mailbox Configurator", 33},
  {"Account", 34},
  {"Type", 35},
  {"Server", 36},
  {"Mailbox Manager", 37},
  {"Edit...", 38},
  {"New...", 39},
  {"Delete...", 40},
  {"Mailboxes/<Separator>", 41},
  {"Get New Mail", 42},
  {"Check POP3", 43},
  {"Exit", 44},
  {"File", 45},
  {"New", 46},
  {"Reply", 47},
  {"Forward", 48},
  {"Message", 49},
  {"Mailbox List", 50},
  {"Close", 51},
  {"Mailboxes", 52},
  {"Preferences...", 53},
  {"Settings", 54},
  {"About", 55},
  {"Help", 56},
  {"Check", 57},
  {"Check Email", 58},
  {"Delete Message", 59},
  {"Compose", 60},
  {"Compose Message", 61},
  {"Previous", 62},
  {"Open Previous Message", 63},
  {"Next", 64},
  {"Open Next Message", 65},
  {"\
The Balsa email client is part of the GNOME desktop environment.  \
Information on Balsa can be found at http://www.balsa.net/\n\
\n\
If you need to report bugs, please do so at: \
http://www.gnome.org/cgi-bin/bugs", 66},
  {"Add Mailbox", 67},
  {"Edit Mailbox", 68},
  {"Identity", 69},
  {"View", 70},
  {"MDI", 71},
  {"Local mail directory:", 72},
  {"Toolbars", 73},
  {"Debug", 74},
  {"Send", 75},
  {"Attach File", 76},
  {"Cut", 77},
  {"Copy", 78},
  {"Paste", 79},
  {"Edit", 80},
  {"Contents", 81},
  {"New message", 82},
  {"Reply to ", 83},
  {"Forward message", 84},
  {"Mailbox: Opening %s Refcount: %d\n", 85},
  {"Mailbox: Closing %s Refcount: %d\n", 86},
  {"Loading message: %s/%s\n", 87},
};

int _msg_tbl_length = 87;
