module Balsa {
  interface SendMail {
    boolean To(in string to);
    boolean Attachment(in string to, in string filename);
  };
  interface MailboxInfo {
    boolean NewMail(in string path);
    long NumMsgs (in string path);
  };
};
