/*
 * This file was generated by orbit-idl - DO NOT EDIT!
 */

#include <glib.h>
#define ORBIT_IDL_SERIAL 2
#include <orb/orbit.h>

#ifdef __cplusplus
extern "C" {
#endif				/* __cplusplus */

/* Begin CORBA module balsa */

/* Begin interface balsa_simple_send */

   /* client-side data structures and methods */
#ifndef _balsa_simple_send_defined
#define _balsa_simple_send_defined

   typedef CORBA_Object balsa_simple_send;
#define balsa_simple_send__free CORBA_Object__free
#endif				/* !_balsa_simple_send_defined */

   extern CORBA_unsigned_long balsa_simple_send__classid;
   extern CORBA_long balsa_simple_send_send_file_as_message(balsa_simple_send _obj, CORBA_char * to, CORBA_char * filename, CORBA_Environment * ev);

   /* server-side (via the POA) data structures and methods */
#ifndef _POA_balsa_simple_send__epv_defined
#define _POA_balsa_simple_send__epv_defined

   typedef struct {
      void *_private;
       CORBA_long(*send_file_as_message) (PortableServer_Servant servant, CORBA_char * to, CORBA_char * filename, CORBA_Environment * ev);
   } POA_balsa_simple_send__epv;
#endif				/* !_POA_balsa_simple_send__epv_defined */

#ifndef _POA_balsa_simple_send__vepv_defined
#define _POA_balsa_simple_send__vepv_defined

   typedef struct {
      PortableServer_ServantBase__epv *_base_epv;
      POA_balsa_simple_send__epv *balsa_simple_send_epv;
   } POA_balsa_simple_send__vepv;
#endif				/* !_POA_balsa_simple_send__vepv_defined */

#ifndef _POA_balsa_simple_send_defined
#define _POA_balsa_simple_send_defined

   typedef struct {
      void *_private;
      POA_balsa_simple_send__vepv *vepv;
   } POA_balsa_simple_send;
#endif				/* !_POA_balsa_simple_send_defined */

   extern void POA_balsa_simple_send__init(POA_balsa_simple_send * servant, CORBA_Environment * ev);
   extern void POA_balsa_simple_send__fini(POA_balsa_simple_send * servant, CORBA_Environment * ev);
/* End interface balsa_simple_send */

/* End CORBA module balsa */

#ifdef __cplusplus
}

#endif				/* __cplusplus */
#undef ORBIT_IDL_SERIAL
