/* Generated by GOB (v0.90.5) on Sun Dec  5 18:19:35 1999
   (do not edit directly) */

#include "balsa-druid-page-welcome.h"

static void balsa_druid_page_welcome_class_init (BalsaDruidPageWelcomeClass *c);
static void balsa_druid_page_welcome_init (BalsaDruidPageWelcome *self);
static void balsa_druid_page_welcome_custom_construct (BalsaDruidPageWelcome *self);
static void balsa_druid_page_welcome_prepare (GnomeDruidPage *_self, GtkWidget *druid);
static gboolean balsa_druid_page_welcome_next (GnomeDruidPage *_self, GtkWidget *druid);
static gboolean balsa_druid_page_welcome_back (GnomeDruidPage *_self, GtkWidget *druid);

static GnomeDruidPageStartClass *parent_class = NULL;

guint
balsa_druid_page_welcome_get_type (void)
{
	static guint type = 0;

	if (!type) {
		static const GtkTypeInfo info = {
			"BalsaDruidPageWelcome",
			sizeof (BalsaDruidPageWelcome),
			sizeof (BalsaDruidPageWelcomeClass),
			(GtkClassInitFunc) balsa_druid_page_welcome_class_init,
			(GtkObjectInitFunc) balsa_druid_page_welcome_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL,
		};

		type = gtk_type_unique (gnome_druid_page_start_get_type(), &info);
	}

	return type;
}


static GtkObject *(* new) (void) = balsa_druid_page_welcome_new;
static void (* custom_construct) (BalsaDruidPageWelcome *self) = balsa_druid_page_welcome_custom_construct;

#define GET_NEW (gtk_type_new(balsa_druid_page_welcome_get_type()))
static void 
balsa_druid_page_welcome_class_init (BalsaDruidPageWelcomeClass *c)
{
	GnomeDruidPageClass *gnome_druid_page_class = (GnomeDruidPageClass *)c;

	parent_class = gtk_type_class (gnome_druid_page_start_get_type ());

	gnome_druid_page_class->prepare = balsa_druid_page_welcome_prepare;
	gnome_druid_page_class->next = balsa_druid_page_welcome_next;
	gnome_druid_page_class->back = balsa_druid_page_welcome_back;
return;
}
#line 36 "balsa-druid-page-welcome.gob"
static void 
balsa_druid_page_welcome_init (BalsaDruidPageWelcome *self)
#line 59 "balsa-druid-page-welcome.c"
{
 {
#line 36 "balsa-druid-page-welcome.gob"

		(GNOME_DRUID_PAGE_START( self ))->title = 
			g_strdup( _("Welcome to Balsa!") );
		(GNOME_DRUID_PAGE_START( self ))->text = 
			g_strdup( _(
	 		"You seem to be running Balsa for the first time. The following\n"
			"steps will set up Balsa by asking a few simple questions. Once\n"
			"you have completed these steps, you can always change them later\n"
			"in Balsa's preferences. Please check the about box in Balsa's\n"
			"main window for more information about contacting the authors or\n"
			"reporting bugs."
			) );
		(GNOME_DRUID_PAGE_START( self ))->logo_image = 
			NULL;
		(GNOME_DRUID_PAGE_START( self ))->watermark_image = 
			balsa_init_get_png( "balsa-watermark.png" );

		balsa_druid_page_welcome_custom_construct( self );
	
#line 82 "balsa-druid-page-welcome.c"
 }
}


#line 34 "balsa-druid-page-welcome.gob"
GtkObject *
balsa_druid_page_welcome_new (void)
{
	{
#line 34 "balsa-druid-page-welcome.gob"
		 GtkObject *me; me = GTK_OBJECT( GET_NEW ); return me; 
#line 94 "balsa-druid-page-welcome.c"
	}
}


#line 56 "balsa-druid-page-welcome.gob"
static void 
balsa_druid_page_welcome_custom_construct (BalsaDruidPageWelcome *self)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (BALSA_IS_DRUID_PAGE_WELCOME (self));
	{
#line 57 "balsa-druid-page-welcome.gob"
		
		GnomeDruidPageStart *start = GNOME_DRUID_PAGE_START( self );

		start->background_item = gnome_canvas_item_new( gnome_canvas_root( GNOME_CANVAS( start->canvas ) ), GNOME_TYPE_CANVAS_RECT, NULL );
		start->textbox_item = gnome_canvas_item_new( gnome_canvas_root( GNOME_CANVAS( start->canvas ) ), GNOME_TYPE_CANVAS_RECT, NULL );
		start->logoframe_item = gnome_canvas_item_new( gnome_canvas_root( GNOME_CANVAS( start->canvas ) ), GNOME_TYPE_CANVAS_RECT, NULL );
		start->logo_item = gnome_canvas_item_new( gnome_canvas_root( GNOME_CANVAS( start->canvas ) ), GNOME_TYPE_CANVAS_IMAGE,
			"image", start->logo_image, NULL );
		start->watermark_item = gnome_canvas_item_new( gnome_canvas_root( GNOME_CANVAS( start->canvas ) ), GNOME_TYPE_CANVAS_IMAGE, 
			"image", start->watermark_image, NULL );
		start->title_item = gnome_canvas_item_new( gnome_canvas_root( GNOME_CANVAS( start->canvas ) ), GNOME_TYPE_CANVAS_TEXT,
			"text", start->title,
			"font", "-adobe-helvetica-bold-r-normal-*-*-180-*-*-p-*-iso8859-1", NULL );
		start->text_item = gnome_canvas_item_new( gnome_canvas_root( GNOME_CANVAS( start->canvas ) ), GNOME_TYPE_CANVAS_TEXT,
			"text", start->text,
			"justification", GTK_JUSTIFY_LEFT,
			"font", "-adobe-helvetica-medium-r-normal-*-*-120-*-*-p-*-iso8859-1", NULL );
	
#line 125 "balsa-druid-page-welcome.c"
	}
}

#line 77 "balsa-druid-page-welcome.gob"
static void 
balsa_druid_page_welcome_prepare (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->prepare) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->prepare)(##args); }
{
	g_return_if_fail (druid != NULL);
	g_return_if_fail (GTK_IS_WIDGET (druid));
	{
#line 78 "balsa-druid-page-welcome.gob"
				
		BalsaDruidPageWelcome *self = BALSA_DRUID_PAGE_WELCOME( _self );

		(GNOME_DRUID_PAGE_START( self ))->logo_image = (BALSA_INITDRUID( druid ))->default_logo;

		gnome_canvas_item_set( (GNOME_DRUID_PAGE_START( self ))->logo_item, "image", 
			(GNOME_DRUID_PAGE_START( self ))->logo_image, NULL );

		gnome_druid_set_buttons_sensitive( GNOME_DRUID( druid ), FALSE, TRUE, TRUE );
		gnome_druid_set_show_finish( GNOME_DRUID( druid ), FALSE );
	
#line 151 "balsa-druid-page-welcome.c"
	}
}
#undef PARENT_HANDLER

#line 90 "balsa-druid-page-welcome.gob"
static gboolean 
balsa_druid_page_welcome_next (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->next) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->next)(##args); }
{
	g_return_val_if_fail (druid != NULL, (gboolean )0);
	g_return_val_if_fail (GTK_IS_WIDGET (druid), (gboolean )0);
	{
#line 91 "balsa-druid-page-welcome.gob"
		
		BalsaDruidPageWelcome *self = BALSA_DRUID_PAGE_WELCOME( _self );

		g_return_val_if_fail( self->next != NULL, FALSE );

		if( BALSA_IS_DRUID_PAGE( self->next ) ) {
			(BALSA_DRUID_PAGE(self->next))->prev = GNOME_DRUID_PAGE( self );
		}

		gnome_druid_set_page( GNOME_DRUID( druid ), GNOME_DRUID_PAGE( self->next ) );
		return TRUE;
	
#line 179 "balsa-druid-page-welcome.c"
	}
}
#undef PARENT_HANDLER

#line 104 "balsa-druid-page-welcome.gob"
static gboolean 
balsa_druid_page_welcome_back (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->back) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->back)(##args); }
{
	g_return_val_if_fail (druid != NULL, (gboolean )0);
	g_return_val_if_fail (GTK_IS_WIDGET (druid), (gboolean )0);
	{
#line 105 "balsa-druid-page-welcome.gob"
		
		g_warning( "Trying to go back from start page... prev button should "
			   "be disabled!" );
		return TRUE;
	
#line 200 "balsa-druid-page-welcome.c"
	}
}
#undef PARENT_HANDLER
#undef GET_NEW


/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method, it pollutes the namespace but the call
  is weird enough.  I need to find a better way to do
  this */
void __balsa_druid_page_welcome_really_bad_hack_to_avoid_warnings(void);
void
__balsa_druid_page_welcome_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))new)();
	((void (*)(void))custom_construct)();
}

