/* Generated by GOB (v1.0.10)   (do not edit directly) */

#include <gtk/gtk.h>

#ifndef __BALSA_DRUID_PAGE_H__
#define __BALSA_DRUID_PAGE_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



/*
 * Balsa E-Mail Client
 * Copyright (C) 1997-1999 Jay Painter and Stuart Parmenter
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option) 
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  
 * 02111-1307, USA.
 */

#include "config.h"
#include <gnome.h>
#include "balsa-druid-page.h"
#include "balsa-initdruid.h"


/*
 * Type checking and casting macros
 */
#define BALSA_TYPE_DRUID_PAGE	(balsa_druid_page_get_type())
#define BALSA_DRUID_PAGE(obj)	GTK_CHECK_CAST((obj), balsa_druid_page_get_type(), BalsaDruidPage)
#define BALSA_DRUID_PAGE_CONST(obj)	GTK_CHECK_CAST((obj), balsa_druid_page_get_type(), BalsaDruidPage const)
#define BALSA_DRUID_PAGE_CLASS(klass)	GTK_CHECK_CLASS_CAST((klass), balsa_druid_page_get_type(), BalsaDruidPageClass)
#define BALSA_IS_DRUID_PAGE(obj)	GTK_CHECK_TYPE((obj), balsa_druid_page_get_type ())

#ifdef GTK_CHECK_GET_CLASS
#define BALSA_DRUID_PAGE_GET_CLASS(obj)	GTK_CHECK_GET_CLASS((obj), balsa_druid_page_get_type(), BalsaDruidPageClass)
#else /* !GTK_CHECK_GET_CLASS */
#define BALSA_DRUID_PAGE_GET_CLASS(obj)	((BalsaDruidPageClass *)GTK_OBJECT(obj)->klass)
#endif /* GTK_CHECK_GET_CLASS */

/*
 * Main object structure
 */
#ifndef __TYPEDEF_BALSA_DRUID_PAGE__
#define __TYPEDEF_BALSA_DRUID_PAGE__
typedef struct _BalsaDruidPage BalsaDruidPage;
#endif
struct _BalsaDruidPage {
	GnomeDruidPageStandard __parent__;
	/*< public >*/
	GnomeDruidPage * prev;
	GnomeDruidPage * next;
	GnomeDruid * druid;
};

/*
 * Class definition
 */
typedef struct _BalsaDruidPageClass BalsaDruidPageClass;
struct _BalsaDruidPageClass {
	GnomeDruidPageStandardClass __parent__;
	void (* construct) (BalsaDruidPage * self);
};


/*
 * Public methods
 */
GtkType	balsa_druid_page_get_type	(void) G_GNUC_CONST;

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
