/* Generated by GOB (v0.90.5)   (do not edit directly) */

#ifndef __BALSA_INITDRUID_H__
#define __BALSA_INITDRUID_H__

#include <gtk/gtk.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



/*
 * Balsa E-Mail Client
 * Copyright (C) 1997-1999 Jay Painter and Stuart Parmenter
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option) 
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  
 * 02111-1307, USA.
 */

#include "config.h"
#include <gnome.h>
#include "helper.h"


#define BALSA_TYPE_INITDRUID	(balsa_initdruid_get_type())
#define BALSA_INITDRUID(obj)	GTK_CHECK_CAST((obj),balsa_initdruid_get_type(),BalsaInitDruid)
#define BALSA_INITDRUID_CLASS(klass)	GTK_CHECK_CLASS_CAST((klass),balsa_initdruid_get_type(),BalsaInitDruidClass)
#define BALSA_IS_INITDRUID(obj)	GTK_CHECK_TYPE((obj), balsa_initdruid_get_type ())


typedef struct _BalsaInitDruid BalsaInitDruid;
struct _BalsaInitDruid {
	GnomeDruid __parent__;
	/* private */ GtkWidget *welcome;
	/* private */ GtkWidget *user;
	/* private */ GtkWidget *std_boxes;
	/* private */ GtkWidget *finish;
	/* private */ GtkWidget *window;
	GdkImlibImage *default_logo;
};

typedef struct _BalsaInitDruidClass BalsaInitDruidClass;
struct _BalsaInitDruidClass {
	GnomeDruidClass __parent__;
};

guint	balsa_initdruid_get_type	(void);
GtkObject *	balsa_initdruid_new	(GtkWindow *window);
void 	balsa_initdruid_finished	(BalsaInitDruid *self);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif