/* Generated by GOB (v0.90.5) on Thu Dec  9 00:46:28 1999
   (do not edit directly) */

#include "balsa-druid-page-directory.h"


#line 29 "balsa-druid-page-directory.gob"

#include "balsa-app.h"

#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include <unistd.h>


#line 19 "balsa-druid-page-directory.c"
static void balsa_druid_page_directory_class_init (BalsaDruidPageDirectoryClass *c);
static void balsa_druid_page_directory_init (BalsaDruidPageDirectory *self);
static void balsa_druid_page_directory_construct (BalsaDruidPage *self);
static void balsa_druid_page_directory_prepare (GnomeDruidPage *_self, GtkWidget *druid);
static gboolean balsa_druid_page_directory_next (GnomeDruidPage *_self, GtkWidget *druid);

static BalsaDruidPageClass *parent_class = NULL;

guint
balsa_druid_page_directory_get_type (void)
{
	static guint type = 0;

	if (!type) {
		static const GtkTypeInfo info = {
			"BalsaDruidPageDirectory",
			sizeof (BalsaDruidPageDirectory),
			sizeof (BalsaDruidPageDirectoryClass),
			(GtkClassInitFunc) balsa_druid_page_directory_class_init,
			(GtkObjectInitFunc) balsa_druid_page_directory_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL,
		};

		type = gtk_type_unique (balsa_druid_page_get_type(), &info);
	}

	return type;
}


static GtkObject *(* new) (BalsaInitDruid *druid) = balsa_druid_page_directory_new;

#define GET_NEW (gtk_type_new(balsa_druid_page_directory_get_type()))
static void 
balsa_druid_page_directory_class_init (BalsaDruidPageDirectoryClass *c)
{
	BalsaDruidPageClass *balsa_druid_page_class = (BalsaDruidPageClass *)c;
	GnomeDruidPageClass *gnome_druid_page_class = (GnomeDruidPageClass *)c;

	parent_class = gtk_type_class (balsa_druid_page_get_type ());

	balsa_druid_page_class->construct = balsa_druid_page_directory_construct;
	gnome_druid_page_class->prepare = balsa_druid_page_directory_prepare;
	gnome_druid_page_class->next = balsa_druid_page_directory_next;
return;
}
#line 63 "balsa-druid-page-directory.gob"
static void 
balsa_druid_page_directory_init (BalsaDruidPageDirectory *self)
#line 71 "balsa-druid-page-directory.c"
{
 {
#line 64 "balsa-druid-page-directory.gob"

		GtkTable *table;
		GtkLabel *label;
		gchar *preset;

		self->emaster.setbits = 0;
		self->emaster.numentries = 0;
		self->emaster.donemask = 0;

		self->ed0.master = &( self->emaster );
		self->ed1.master = &( self->emaster );
		self->ed2.master = &( self->emaster );
		self->ed3.master = &( self->emaster );
		self->ed4.master = &( self->emaster );

		table = GTK_TABLE( gtk_table_new( 6, 2, FALSE ) );
	
		label = GTK_LABEL( gtk_label_new( _(
			"Please confirm the locations of your default mail files.\n"
			"These will be created if necessary." ) ) );
		gtk_label_set_justify( label, GTK_JUSTIFY_RIGHT );
		gtk_label_set_line_wrap( label, TRUE );
		gtk_table_attach( table, GTK_WIDGET( label ), 0, 2, 0, 1,
			GTK_EXPAND | GTK_FILL, GTK_EXPAND | GTK_FILL,
			8, 4 );

		preset = getenv( "MAIL" );
		if( preset )
			preset = g_strdup( preset );
		balsa_init_add_table_entry( table, 0, _("Inbox:"), preset, &( self->ed0 ), GTK_WIDGET( self ), &( self->inbox ) );
		if( preset )
			g_free( preset );

		preset = g_strconcat( balsa_app.local_mail_directory, "/outbox", NULL );
		balsa_init_add_table_entry( table, 1, _("Outbox:"), preset, &( self->ed1 ), GTK_WIDGET( self ), &( self->outbox ) );
		g_free( preset );

		preset = g_strconcat( balsa_app.local_mail_directory, "/sentbox", NULL );
		balsa_init_add_table_entry( table, 2, _("Sentbox:"), preset, &( self->ed2 ), GTK_WIDGET( self ), &( self->sentbox ) );
		g_free( preset );

		preset = g_strconcat( balsa_app.local_mail_directory, "/draftbox", NULL );
		balsa_init_add_table_entry( table, 3, _("Draftbox:"), preset, &( self->ed3 ), GTK_WIDGET( self ), &( self->draftbox ) );
		g_free( preset );

		preset = g_strconcat( balsa_app.local_mail_directory, "/trash", NULL );
		balsa_init_add_table_entry( table, 4, _("Trash:"), preset, &( self->ed4 ), GTK_WIDGET( self ), &( self->trash ) );
		g_free( preset );

		gtk_box_pack_start( GTK_BOX( (GNOME_DRUID_PAGE_STANDARD( self ))->vbox ),
			GTK_WIDGET( table ), TRUE, TRUE, 8 );
		gtk_widget_show_all( GTK_WIDGET( table ) );
	
#line 128 "balsa-druid-page-directory.c"
 }
}


#line 55 "balsa-druid-page-directory.gob"
GtkObject *
balsa_druid_page_directory_new (BalsaInitDruid *druid)
{
	g_return_val_if_fail (BALSA_IS_INITDRUID (druid), (GtkObject *)0);
	g_return_val_if_fail (druid != NULL, (GtkObject *)0);
	{
#line 56 "balsa-druid-page-directory.gob"
		 
		GtkObject *self = GTK_OBJECT( GET_NEW );
		(BALSA_DRUID_PAGE( self ))->druid = GNOME_DRUID( druid );
		balsa_druid_page_directory_construct( BALSA_DRUID_PAGE( self ) );
		return self;
	
#line 147 "balsa-druid-page-directory.c"
	}
}


#line 118 "balsa-druid-page-directory.gob"
static void 
balsa_druid_page_directory_construct (BalsaDruidPage *self)
#define PARENT_HANDLER(args...) \
	{ if(BALSA_DRUID_PAGE_CLASS(parent_class)->construct) \
		(* BALSA_DRUID_PAGE_CLASS(parent_class)->construct)(##args); }
{
	{
#line 120 "balsa-druid-page-directory.gob"
		
		(GNOME_DRUID_PAGE_STANDARD( self ))->title = g_strdup( _("Mail Files" ) );

		g_return_if_fail( (BALSA_DRUID_PAGE( self ))->druid != NULL );
		(GNOME_DRUID_PAGE_STANDARD( self ))->logo_image = (BALSA_INITDRUID( (BALSA_DRUID_PAGE( self ))->druid ))->default_logo;

		PARENT_HANDLER( self );
	
#line 169 "balsa-druid-page-directory.c"
	}
}
#undef PARENT_HANDLER

#line 129 "balsa-druid-page-directory.gob"
static void 
balsa_druid_page_directory_prepare (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->prepare) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->prepare)(##args); }
{
	g_return_if_fail (GTK_IS_WIDGET (druid));
	g_return_if_fail (druid != NULL);
	{
#line 131 "balsa-druid-page-directory.gob"
		
		BalsaDruidPageDirectory *self = BALSA_DRUID_PAGE_DIRECTORY( _self );

		/* Don't let them continue unless all entries have something. */

		if( ENTRY_MASTER_DONE( self->emaster ) ) {
			gnome_druid_set_buttons_sensitive( GNOME_DRUID( druid ), TRUE, TRUE, TRUE );
		} else {
			gnome_druid_set_buttons_sensitive( GNOME_DRUID( druid ), TRUE, FALSE, TRUE );
		}

		gnome_druid_set_show_finish( GNOME_DRUID( druid ), FALSE );
	
#line 198 "balsa-druid-page-directory.c"
	}
}
#undef PARENT_HANDLER

#line 145 "balsa-druid-page-directory.gob"
static gboolean 
balsa_druid_page_directory_next (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->next) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->next)(##args); }
{
	g_return_val_if_fail (GTK_IS_WIDGET (druid), (gboolean )0);
	g_return_val_if_fail (druid != NULL, (gboolean )0);
	{
#line 147 "balsa-druid-page-directory.gob"
		
		BalsaDruidPageDirectory *self = BALSA_DRUID_PAGE_DIRECTORY( _self );	

		PARENT_HANDLER( _self, druid );
		return TRUE;
	
#line 220 "balsa-druid-page-directory.c"
	}
}
#undef PARENT_HANDLER
#undef GET_NEW


/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method, it pollutes the namespace but the call
  is weird enough.  I need to find a better way to do
  this */
void __balsa_druid_page_directory_really_bad_hack_to_avoid_warnings(void);
void
__balsa_druid_page_directory_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))new)();
}

