/* Generated by GOB (v0.90.5)   (do not edit directly) */

#ifndef __BALSA_DRUID_PAGE_USER_H__
#define __BALSA_DRUID_PAGE_USER_H__

#include <gtk/gtk.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



/*
 * Balsa E-Mail Client
 * Copyright (C) 1997-1999 Jay Painter and Stuart Parmenter
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option) 
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of 
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the  
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  
 * 02111-1307, USA.
 */

#include "config.h"
#include <gnome.h>
#include "helper.h"
#include "balsa-initdruid.h"
#include "balsa-druid-page.h"

typedef struct EntryData_s EntryData;
struct EntryData_s {
	GtkWidget *page;
	guint num;
};


#define BALSA_TYPE_DRUID_PAGE_USER	(balsa_druid_page_user_get_type())
#define BALSA_DRUID_PAGE_USER(obj)	GTK_CHECK_CAST((obj),balsa_druid_page_user_get_type(),BalsaDruidPageUser)
#define BALSA_DRUID_PAGE_USER_CLASS(klass)	GTK_CHECK_CLASS_CAST((klass),balsa_druid_page_user_get_type(),BalsaDruidPageUserClass)
#define BALSA_IS_DRUID_PAGE_USER(obj)	GTK_CHECK_TYPE((obj), balsa_druid_page_user_get_type ())


typedef struct _BalsaDruidPageUser BalsaDruidPageUser;
struct _BalsaDruidPageUser {
	BalsaDruidPage __parent__;
	/* private */ guint32 setbits;
	/* private */ guint32 numentries;
	/* private */ EntryData ed0;
	/* private */ EntryData ed1;
	/* private */ EntryData ed2;
	/* private */ EntryData ed3;
};

typedef struct _BalsaDruidPageUserClass BalsaDruidPageUserClass;
struct _BalsaDruidPageUserClass {
	BalsaDruidPageClass __parent__;
};

guint	balsa_druid_page_user_get_type	(void);
GtkObject *	balsa_druid_page_user_new	(BalsaInitDruid *druid);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif