/* Generated by GOB (v0.90.5) on Tue Dec 21 17:43:57 1999
   (do not edit directly) */

#include "balsa-druid-page-finish.h"


#line 29 "balsa-druid-page-finish.gob"

#include "save-restore.h"

#line 12 "balsa-druid-page-finish.c"
static void balsa_druid_page_finish_class_init (BalsaDruidPageFinishClass *c);
static void balsa_druid_page_finish_init (BalsaDruidPageFinish *self);
static void balsa_druid_page_finish_construct (BalsaDruidPage *self);
static void balsa_druid_page_finish_prepare (GnomeDruidPage *_self, GtkWidget *druid);
static void balsa_druid_page_finish_finish (GnomeDruidPage *_self, GtkWidget *druid);

static BalsaDruidPageClass *parent_class = NULL;

guint
balsa_druid_page_finish_get_type (void)
{
	static guint type = 0;

	if (!type) {
		static const GtkTypeInfo info = {
			"BalsaDruidPageFinish",
			sizeof (BalsaDruidPageFinish),
			sizeof (BalsaDruidPageFinishClass),
			(GtkClassInitFunc) balsa_druid_page_finish_class_init,
			(GtkObjectInitFunc) balsa_druid_page_finish_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL,
		};

		type = gtk_type_unique (balsa_druid_page_get_type(), &info);
	}

	return type;
}


static GtkObject *(* new) (void) = balsa_druid_page_finish_new;

#define GET_NEW (gtk_type_new(balsa_druid_page_finish_get_type()))
static void 
balsa_druid_page_finish_class_init (BalsaDruidPageFinishClass *c)
{
	BalsaDruidPageClass *balsa_druid_page_class = (BalsaDruidPageClass *)c;
	GnomeDruidPageClass *gnome_druid_page_class = (GnomeDruidPageClass *)c;

	parent_class = gtk_type_class (balsa_druid_page_get_type ());

	balsa_druid_page_class->construct = balsa_druid_page_finish_construct;
	gnome_druid_page_class->prepare = balsa_druid_page_finish_prepare;
	gnome_druid_page_class->finish = balsa_druid_page_finish_finish;
return;
}
#line 42 "balsa-druid-page-finish.gob"
static void 
balsa_druid_page_finish_init (BalsaDruidPageFinish *self)
#line 64 "balsa-druid-page-finish.c"
{
 {
#line 42 "balsa-druid-page-finish.gob"

		self->text = gtk_label_new( _(
			"You've successfully set up Balsa. Have fun!\n"
			"   -- The Balsa development team"
			) );
		gtk_label_set_justify( GTK_LABEL( self->text ), GTK_JUSTIFY_CENTER );
		gtk_box_pack_start( GTK_BOX( (GNOME_DRUID_PAGE_STANDARD( self ))->vbox ), GTK_WIDGET( self->text ),
			TRUE, TRUE, 8 );
	
#line 77 "balsa-druid-page-finish.c"
 }
}


#line 36 "balsa-druid-page-finish.gob"
GtkObject *
balsa_druid_page_finish_new (void)
{
	{
#line 36 "balsa-druid-page-finish.gob"
		 
		GtkObject *self = GTK_OBJECT( GET_NEW );
		balsa_druid_page_finish_construct( BALSA_DRUID_PAGE( self ) );
		return self;
	 
#line 93 "balsa-druid-page-finish.c"
	}
}


#line 52 "balsa-druid-page-finish.gob"
static void 
balsa_druid_page_finish_construct (BalsaDruidPage *self)
#define PARENT_HANDLER(args...) \
	{ if(BALSA_DRUID_PAGE_CLASS(parent_class)->construct) \
		(* BALSA_DRUID_PAGE_CLASS(parent_class)->construct)(##args); }
{
	{
#line 53 "balsa-druid-page-finish.gob"
		
		GnomeDruidPageStandard *std = GNOME_DRUID_PAGE_STANDARD( self );

		std->title = g_strdup( _("All Done!") );
		PARENT_HANDLER( self );
	
#line 113 "balsa-druid-page-finish.c"
	}
}
#undef PARENT_HANDLER

#line 60 "balsa-druid-page-finish.gob"
static void 
balsa_druid_page_finish_prepare (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->prepare) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->prepare)(##args); }
{
	g_return_if_fail (GTK_IS_WIDGET (druid));
	g_return_if_fail (druid != NULL);
	{
#line 61 "balsa-druid-page-finish.gob"
		
		BalsaDruidPageFinish *self = BALSA_DRUID_PAGE_FINISH( _self );

		gnome_druid_page_standard_set_logo( GNOME_DRUID_PAGE_STANDARD( self ), (BALSA_INITDRUID( druid ))->default_logo );
		gnome_druid_set_buttons_sensitive( GNOME_DRUID( druid ), TRUE, FALSE, TRUE );
		gnome_druid_set_show_finish( GNOME_DRUID( druid ), TRUE );
	
#line 136 "balsa-druid-page-finish.c"
	}
}
#undef PARENT_HANDLER

#line 69 "balsa-druid-page-finish.gob"
static void 
balsa_druid_page_finish_finish (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->finish) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->finish)(##args); }
{
	g_return_if_fail (GTK_IS_WIDGET (druid));
	g_return_if_fail (druid != NULL);
	{
#line 70 "balsa-druid-page-finish.gob"
		
		config_global_save();
		balsa_initdruid_finished( BALSA_INITDRUID( druid ) );
	
#line 156 "balsa-druid-page-finish.c"
	}
}
#undef PARENT_HANDLER
#undef GET_NEW


/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method, it pollutes the namespace but the call
  is weird enough.  I need to find a better way to do
  this */
void __balsa_druid_page_finish_really_bad_hack_to_avoid_warnings(void);
void
__balsa_druid_page_finish_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))new)();
}

