/* Generated by GOB (v0.90.5) on Tue Dec  7 23:00:24 1999
   (do not edit directly) */

#include "balsa-druid-page-user.h"


#line 35 "balsa-druid-page-user.gob"

#include "balsa-druid-page-error.h"

#define ENTRIES 4
	
/* Warning: these functions are all very interdependent. Make sure to keep assumptions
 * consistent when modifying.
 */
static void entrylabel( GtkTable *table, guint num, gchar *ltext, gchar *etext, EntryData *ed, GtkWidget *page );
static void entry_changed_cb( GtkEntry *entry );

static void entrylabel( GtkTable *table, guint num, gchar *ltext, gchar *etext, EntryData *ed, GtkWidget *page )
{
	GtkWidget *w;

	ed->num = num;
	ed->page = page;

	w = gtk_label_new( ltext );
	gtk_label_set_justify( GTK_LABEL( w ), GTK_JUSTIFY_RIGHT );
	gtk_table_attach( table, GTK_WIDGET( w ), 0, 1, num + 1, num + 2,
		GTK_EXPAND | GTK_FILL, GTK_EXPAND | GTK_FILL,
		8, 4 );

	w = gtk_entry_new();
	gtk_object_set_user_data( GTK_OBJECT( w ), ed );
	gtk_entry_set_text( GTK_ENTRY( w ), etext );
	gtk_signal_connect( GTK_OBJECT( w ), "changed", entry_changed_cb, NULL );
	gtk_table_attach( table, GTK_WIDGET( w ), 1, 2, num + 1, num + 2,
		GTK_EXPAND | GTK_FILL, GTK_EXPAND | GTK_FILL,
		8, 4 );
}

static void entry_changed_cb( GtkEntry *entry )
{
	EntryData *ed = gtk_object_get_user_data( GTK_OBJECT( entry ) );
	BalsaDruidPageUser *up;
	guint32 donemask;

	g_assert( ed != NULL );

	up = BALSA_DRUID_PAGE_USER( ed->page );
	if( entry->text_length ) {
		up->setbits |= (1 << ed->num);
	} else {
		up->setbits &= ~(1 << ed->num);
	}

	/* The stuff below is only when we are displayed... which is not
	 * always the case.
	 */
	if( !GTK_WIDGET_VISIBLE( GTK_WIDGET( entry ) ) )
		return;

	/* numentries = say, 3;
	 * 1 << 3 = 01000b
	 * 01000b - 1 = 0111b
	 */
	donemask = ( (1 << up->numentries) - 1 );

	/* Don't let them continue unless all entries have something. */
	if( (up->setbits & donemask) == donemask ) {
		gnome_druid_set_buttons_sensitive( GNOME_DRUID( (BALSA_DRUID_PAGE( up ))->druid ), TRUE, TRUE, TRUE );
	} else {
		gnome_druid_set_buttons_sensitive( GNOME_DRUID( (BALSA_DRUID_PAGE( up ))->druid ), TRUE, FALSE, TRUE );
	}
}


#line 78 "balsa-druid-page-user.c"
static void balsa_druid_page_user_class_init (BalsaDruidPageUserClass *c);
static void balsa_druid_page_user_init (BalsaDruidPageUser *self);
static void balsa_druid_page_user_construct (BalsaDruidPage *self);
static void balsa_druid_page_user_prepare (GnomeDruidPage *_self, GtkWidget *druid);
static gboolean balsa_druid_page_user_next (GnomeDruidPage *_self, GtkWidget *druid);

static BalsaDruidPageClass *parent_class = NULL;

guint
balsa_druid_page_user_get_type (void)
{
	static guint type = 0;

	if (!type) {
		static const GtkTypeInfo info = {
			"BalsaDruidPageUser",
			sizeof (BalsaDruidPageUser),
			sizeof (BalsaDruidPageUserClass),
			(GtkClassInitFunc) balsa_druid_page_user_class_init,
			(GtkObjectInitFunc) balsa_druid_page_user_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL,
		};

		type = gtk_type_unique (balsa_druid_page_get_type(), &info);
	}

	return type;
}


static GtkObject *(* new) (BalsaInitDruid *druid) = balsa_druid_page_user_new;

#define GET_NEW (gtk_type_new(balsa_druid_page_user_get_type()))
static void 
balsa_druid_page_user_class_init (BalsaDruidPageUserClass *c)
{
	BalsaDruidPageClass *balsa_druid_page_class = (BalsaDruidPageClass *)c;
	GnomeDruidPageClass *gnome_druid_page_class = (GnomeDruidPageClass *)c;

	parent_class = gtk_type_class (balsa_druid_page_get_type ());

	balsa_druid_page_class->construct = balsa_druid_page_user_construct;
	gnome_druid_page_class->prepare = balsa_druid_page_user_prepare;
	gnome_druid_page_class->next = balsa_druid_page_user_next;
return;
}
#line 122 "balsa-druid-page-user.gob"
static void 
balsa_druid_page_user_init (BalsaDruidPageUser *self)
#line 130 "balsa-druid-page-user.c"
{
 {
#line 122 "balsa-druid-page-user.gob"

		GtkTable *table;
		GtkLabel *label;
		gchar *preset;
		char hostbuf[512];

		self->numentries = ENTRIES;
		self->setbits = 0xFF;

		table = GTK_TABLE( gtk_table_new( 5, 2, FALSE ) );

		label = GTK_LABEL( gtk_label_new( _("Please enter information about yourself.") ) );
		gtk_label_set_justify( label, GTK_JUSTIFY_CENTER );
		gtk_label_set_line_wrap( label, TRUE );
		gtk_table_attach( table, GTK_WIDGET( label ), 0, 2, 0, 1,
			GTK_EXPAND | GTK_FILL, GTK_EXPAND | GTK_FILL, 
			8, 4 );

		preset = g_get_real_name();
		entrylabel( table, 0, _("Name:"), preset, &( self->ed0 ), GTK_WIDGET( self ) );
		
		gethostname( hostbuf, 511 );
		preset = g_strconcat( g_get_user_name(), "@", hostbuf, NULL );
		entrylabel( table, 1, _("Email address:"), preset, &( self->ed1 ), GTK_WIDGET( self ) );
		g_free( preset );

		preset = "localhost";
		entrylabel( table, 2, _("SMTP Server:"), preset, &( self->ed2 ), GTK_WIDGET( self ) );

		preset = g_strconcat( g_get_home_dir(), "/balsa", NULL );
		entrylabel( table, 3, _("Local Mail Directory:"), preset, &( self->ed3 ), GTK_WIDGET( self ) );
		g_free( preset );

		gtk_box_pack_start( GTK_BOX( (GNOME_DRUID_PAGE_STANDARD( self ))->vbox ),
			GTK_WIDGET( table ), TRUE, TRUE, 8 );
		gtk_widget_show_all( GTK_WIDGET( table ) );
	
#line 171 "balsa-druid-page-user.c"
 }
}


#line 114 "balsa-druid-page-user.gob"
GtkObject *
balsa_druid_page_user_new (BalsaInitDruid *druid)
{
	g_return_val_if_fail (BALSA_IS_INITDRUID (druid), (GtkObject *)0);
	g_return_val_if_fail (druid != NULL, (GtkObject *)0);
	{
#line 115 "balsa-druid-page-user.gob"
		 
		GtkObject *self = GTK_OBJECT( GET_NEW );
		(BALSA_DRUID_PAGE( self ))->druid = GNOME_DRUID( druid );
		balsa_druid_page_user_construct( BALSA_DRUID_PAGE( self ) );
		return self;
	
#line 190 "balsa-druid-page-user.c"
	}
}


#line 160 "balsa-druid-page-user.gob"
static void 
balsa_druid_page_user_construct (BalsaDruidPage *self)
#define PARENT_HANDLER(args...) \
	{ if(BALSA_DRUID_PAGE_CLASS(parent_class)->construct) \
		(* BALSA_DRUID_PAGE_CLASS(parent_class)->construct)(##args); }
{
	{
#line 161 "balsa-druid-page-user.gob"
		
		(GNOME_DRUID_PAGE_STANDARD( self ))->title = g_strdup( _("User Settings" ) );

		g_return_if_fail( (BALSA_DRUID_PAGE( self ))->druid != NULL );
		(GNOME_DRUID_PAGE_STANDARD( self ))->logo_image = (BALSA_INITDRUID( (BALSA_DRUID_PAGE( self ))->druid ))->default_logo;

		PARENT_HANDLER( self );
	
#line 212 "balsa-druid-page-user.c"
	}
}
#undef PARENT_HANDLER

#line 170 "balsa-druid-page-user.gob"
static void 
balsa_druid_page_user_prepare (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->prepare) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->prepare)(##args); }
{
	g_return_if_fail (GTK_IS_WIDGET (druid));
	g_return_if_fail (druid != NULL);
	{
#line 171 "balsa-druid-page-user.gob"
		
		guint32 donemask;
		BalsaDruidPageUser *self = BALSA_DRUID_PAGE_USER( _self );

		/* Don't let them continue unless all entries have something. */
		/* FIXME: unify this with code above */
		donemask = ( (1 << self->numentries) - 1 );

		if( (self->setbits & donemask) == donemask ) {
			gnome_druid_set_buttons_sensitive( GNOME_DRUID( druid ), TRUE, TRUE, TRUE );
		} else {
			gnome_druid_set_buttons_sensitive( GNOME_DRUID( druid ), TRUE, FALSE, TRUE );
		}

		gnome_druid_set_show_finish( GNOME_DRUID( druid ), FALSE );
	
#line 244 "balsa-druid-page-user.c"
	}
}
#undef PARENT_HANDLER

#line 188 "balsa-druid-page-user.gob"
static gboolean 
balsa_druid_page_user_next (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->next) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->next)(##args); }
{
	g_return_val_if_fail (GTK_IS_WIDGET (druid), (gboolean )0);
	g_return_val_if_fail (druid != NULL, (gboolean )0);
	{
#line 189 "balsa-druid-page-user.gob"
		
		static gboolean tested_it = FALSE;

		if( !tested_it ) {
			GtkObject *next;

			next = balsa_druid_page_error_new_after( BALSA_DRUID_PAGE( _self ), "Aieee!!!" );
			gtk_box_pack_start( GTK_BOX( (GNOME_DRUID_PAGE_STANDARD( next ))->vbox ),
				GTK_WIDGET( gtk_label_new( "Test" ) ), TRUE, TRUE, 8 );
			gtk_widget_show_all( GTK_WIDGET( (GNOME_DRUID_PAGE_STANDARD( next ))->vbox ) );
			balsa_druid_page_error_goto_me( next );
			tested_it = TRUE;
		} else {
			PARENT_HANDLER( _self, druid );
		}

		return TRUE;
	
#line 278 "balsa-druid-page-user.c"
	}
}
#undef PARENT_HANDLER
#undef GET_NEW


/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method, it pollutes the namespace but the call
  is weird enough.  I need to find a better way to do
  this */
void __balsa_druid_page_user_really_bad_hack_to_avoid_warnings(void);
void
__balsa_druid_page_user_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))new)();
}

