/* Generated by GOB (v0.90.5) on Tue Dec 21 17:43:57 1999
   (do not edit directly) */

#include "balsa-druid-page-error.h"


#line 29 "balsa-druid-page-error.gob"

#include <errno.h>

#line 12 "balsa-druid-page-error.c"
static void balsa_druid_page_error_class_init (BalsaDruidPageErrorClass *c);
static void balsa_druid_page_error_init (BalsaDruidPageError *self);
static void balsa_druid_page_error_construct (BalsaDruidPage *self);
static void balsa_druid_page_error_prepare (GnomeDruidPage *_self, GtkWidget *druid);
static gboolean balsa_druid_page_error_back (GnomeDruidPage *_self, GtkWidget *druid);

static BalsaDruidPageClass *parent_class = NULL;

guint
balsa_druid_page_error_get_type (void)
{
	static guint type = 0;

	if (!type) {
		static const GtkTypeInfo info = {
			"BalsaDruidPageError",
			sizeof (BalsaDruidPageError),
			sizeof (BalsaDruidPageErrorClass),
			(GtkClassInitFunc) balsa_druid_page_error_class_init,
			(GtkObjectInitFunc) balsa_druid_page_error_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL,
		};

		type = gtk_type_unique (balsa_druid_page_get_type(), &info);
	}

	return type;
}


static GtkObject *(* new_after) (BalsaDruidPage *prev, gchar *title, gchar *text) = balsa_druid_page_error_new_after;
static void (* goto_me) (BalsaDruidPageError *self) = balsa_druid_page_error_goto_me;

#define GET_NEW (gtk_type_new(balsa_druid_page_error_get_type()))
static void 
balsa_druid_page_error_class_init (BalsaDruidPageErrorClass *c)
{
	BalsaDruidPageClass *balsa_druid_page_class = (BalsaDruidPageClass *)c;
	GnomeDruidPageClass *gnome_druid_page_class = (GnomeDruidPageClass *)c;

	parent_class = gtk_type_class (balsa_druid_page_get_type ());

	balsa_druid_page_class->construct = balsa_druid_page_error_construct;
	gnome_druid_page_class->prepare = balsa_druid_page_error_prepare;
	gnome_druid_page_class->back = balsa_druid_page_error_back;
return;
}
#line 63 "balsa-druid-page-error.gob"
static void 
balsa_druid_page_error_init (BalsaDruidPageError *self)
#line 65 "balsa-druid-page-error.c"
{
 {
#line 63 "balsa-druid-page-error.gob"

		GdkColor alarm;

		alarm.red = 40000; alarm.blue = 0; alarm.green = 0;		
		gnome_druid_page_standard_set_bg_color( GNOME_DRUID_PAGE_STANDARD( self ), &alarm );
	
#line 75 "balsa-druid-page-error.c"
 }
}


#line 37 "balsa-druid-page-error.gob"
GtkObject *
balsa_druid_page_error_new_after (BalsaDruidPage *prev, gchar *title, gchar *text)
{
	g_return_val_if_fail (prev != NULL, (GtkObject *)0);
	g_return_val_if_fail (BALSA_IS_DRUID_PAGE (prev), (GtkObject *)0);
	g_return_val_if_fail (title != NULL, (GtkObject *)0);
	g_return_val_if_fail (text != NULL, (GtkObject *)0);
	{
#line 37 "balsa-druid-page-error.gob"
		
		BalsaDruidPageError *self = BALSA_DRUID_PAGE_ERROR( GET_NEW );

		self->real_next = prev->next;
		self->text = g_strdup( text );
		prev->next = GNOME_DRUID_PAGE( self );
		(BALSA_DRUID_PAGE( self ))->prev = GNOME_DRUID_PAGE( prev );
		(BALSA_DRUID_PAGE( self ))->next = NULL;
		(BALSA_DRUID_PAGE( self ))->druid = (BALSA_DRUID_PAGE( prev ))->druid;
	
		balsa_druid_page_error_construct( BALSA_DRUID_PAGE( self ) );
		gnome_druid_page_standard_set_title( GNOME_DRUID_PAGE_STANDARD( self ), title );
		gnome_druid_page_standard_set_logo( GNOME_DRUID_PAGE_STANDARD( self ), 
			(BALSA_INITDRUID( (BALSA_DRUID_PAGE( self ))->druid ))->default_logo );
		gnome_druid_append_page( GNOME_DRUID( prev->druid ), GNOME_DRUID_PAGE( self ) );
		return GTK_OBJECT( self );
	
#line 107 "balsa-druid-page-error.c"
	}
}

#line 55 "balsa-druid-page-error.gob"
void 
balsa_druid_page_error_goto_me (BalsaDruidPageError *self)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (BALSA_IS_DRUID_PAGE_ERROR (self));
	{
#line 56 "balsa-druid-page-error.gob"
		
		BalsaInitDruid *druid = BALSA_INITDRUID( (BALSA_DRUID_PAGE( self ))->druid );

		(BALSA_DRUID_PAGE( (BALSA_DRUID_PAGE( self ))->prev ))->next = GNOME_DRUID_PAGE( self );
		gnome_druid_set_page( GNOME_DRUID( druid ), GNOME_DRUID_PAGE( self ) );
	
#line 125 "balsa-druid-page-error.c"
	}
}


#line 70 "balsa-druid-page-error.gob"
static void 
balsa_druid_page_error_construct (BalsaDruidPage *self)
#define PARENT_HANDLER(args...) \
	{ if(BALSA_DRUID_PAGE_CLASS(parent_class)->construct) \
		(* BALSA_DRUID_PAGE_CLASS(parent_class)->construct)(##args); }
{
	{
#line 71 "balsa-druid-page-error.gob"
		
		GtkWidget *label;
		gchar *errtext;

		PARENT_HANDLER( self );

		label = gtk_label_new( (BALSA_DRUID_PAGE_ERROR( self ))->text );
		gtk_box_pack_start( GTK_BOX( (GNOME_DRUID_PAGE_STANDARD( self ))->vbox ), label, TRUE, TRUE, 8 );

		errtext = g_strdup_printf( "Technical Information:\n"
			"errno = %d (%s)", errno, g_strerror( errno ) );
		label = gtk_label_new( errtext );
		g_free( errtext );
		gtk_box_pack_start( GTK_BOX( (GNOME_DRUID_PAGE_STANDARD( self ))->vbox ), label, TRUE, TRUE, 8 );

		gtk_widget_show_all( GTK_WIDGET( self ) );
	
#line 156 "balsa-druid-page-error.c"
	}
}
#undef PARENT_HANDLER

#line 89 "balsa-druid-page-error.gob"
static void 
balsa_druid_page_error_prepare (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->prepare) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->prepare)(##args); }
{
	g_return_if_fail (GTK_IS_WIDGET (druid));
	g_return_if_fail (druid != NULL);
	{
#line 90 "balsa-druid-page-error.gob"
		
		/*BalsaDruidPageFinish *self = BALSA_DRUID_PAGE_FINISH( _self );*/

		/*gnome_druid_page_standard_set_logo( GNOME_DRUID_PAGE_STANDARD( self ), (BALSA_INITDRUID( druid ))->default_logo );*/
		gnome_druid_set_buttons_sensitive( GNOME_DRUID( druid ), TRUE, FALSE, TRUE );
		gnome_druid_set_show_finish( GNOME_DRUID( druid ), FALSE );
		PARENT_HANDLER( _self, druid );
	
#line 180 "balsa-druid-page-error.c"
	}
}
#undef PARENT_HANDLER

#line 99 "balsa-druid-page-error.gob"
static gboolean 
balsa_druid_page_error_back (GnomeDruidPage *_self, GtkWidget *druid)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_PAGE_CLASS(parent_class)->back) \
		(* GNOME_DRUID_PAGE_CLASS(parent_class)->back)(##args); }
{
	g_return_val_if_fail (GTK_IS_WIDGET (druid), (gboolean )0);
	g_return_val_if_fail (druid != NULL, (gboolean )0);
	{
#line 100 "balsa-druid-page-error.gob"
		
		BalsaDruidPage *self = BALSA_DRUID_PAGE( _self );

		g_return_val_if_fail( self->prev != NULL, TRUE );

		(BALSA_DRUID_PAGE( self->prev ))->next = (BALSA_DRUID_PAGE_ERROR( self ))->real_next;
		gnome_druid_set_page( GNOME_DRUID( (BALSA_DRUID_PAGE( self ))->druid ), GNOME_DRUID_PAGE( self->prev ) );
		gtk_object_destroy( GTK_OBJECT( self ) );
		return TRUE;
	
#line 206 "balsa-druid-page-error.c"
	}
}
#undef PARENT_HANDLER
#undef GET_NEW


/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method, it pollutes the namespace but the call
  is weird enough.  I need to find a better way to do
  this */
void __balsa_druid_page_error_really_bad_hack_to_avoid_warnings(void);
void
__balsa_druid_page_error_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))new_after)();
	((void (*)(void))goto_me)();
}

