/* Generated by GOB (v0.90.5) on Sun Dec  5 18:24:23 1999
   (do not edit directly) */

#include "balsa-initdruid.h"


#line 27 "balsa-initdruid.gob"

#include "balsa-druid-page.h"
#include "balsa-druid-page-welcome.h"
#include "balsa-druid-page-finish.h"

static void really_cb( gint reply, BalsaInitDruid *druid );

static void really_cb( gint reply, BalsaInitDruid *druid )
{
    if( reply == GNOME_YES ) {
	balsa_initdruid_finished( druid );
	gtk_exit( 0 );
    }
}

static void joojuyfruits( void );

static void joojuyfruits( void )
{
}

#line 30 "balsa-initdruid.c"
static void balsa_initdruid_class_init (BalsaInitDruidClass *c);
static void balsa_initdruid_init (BalsaInitDruid *self);
static void balsa_initdruid_cancel (GnomeDruid *_self);

static GnomeDruidClass *parent_class = NULL;

guint
balsa_initdruid_get_type (void)
{
	static guint type = 0;

	if (!type) {
		static const GtkTypeInfo info = {
			"BalsaInitDruid",
			sizeof (BalsaInitDruid),
			sizeof (BalsaInitDruidClass),
			(GtkClassInitFunc) balsa_initdruid_class_init,
			(GtkObjectInitFunc) balsa_initdruid_init,
			/* reserved_1 */ NULL,
			/* reserved_2 */ NULL,
			(GtkClassInitFunc) NULL,
		};

		type = gtk_type_unique (gnome_druid_get_type(), &info);
	}

	return type;
}


static GtkObject *(* new) (GtkWindow *window) = balsa_initdruid_new;
static void (* finished) (BalsaInitDruid *self) = balsa_initdruid_finished;

#define GET_NEW (gtk_type_new(balsa_initdruid_get_type()))
static void 
balsa_initdruid_class_init (BalsaInitDruidClass *c)
{
	GnomeDruidClass *gnome_druid_class = (GnomeDruidClass *)c;

	parent_class = gtk_type_class (gnome_druid_get_type ());

	gnome_druid_class->cancel = balsa_initdruid_cancel;
return;
}
#line 65 "balsa-initdruid.gob"
static void 
balsa_initdruid_init (BalsaInitDruid *self)
#line 78 "balsa-initdruid.c"
{
 {
#line 65 "balsa-initdruid.gob"

		joojuyfruits();

		self->welcome = GTK_WIDGET( balsa_druid_page_welcome_new() );
		gnome_druid_append_page( GNOME_DRUID( self ), GNOME_DRUID_PAGE( self->welcome ) );
	        gnome_druid_set_page( GNOME_DRUID( self ), GNOME_DRUID_PAGE( self->welcome ) );

		self->user = NULL;
		self->std_boxes = NULL;

		self->finish = GTK_WIDGET( balsa_druid_page_finish_new() );
		gnome_druid_append_page( GNOME_DRUID( self ), GNOME_DRUID_PAGE( self->finish ) );

		(BALSA_DRUID_PAGE_WELCOME( self->welcome ))->next = self->finish;

		self->default_logo = balsa_init_get_png( "balsa-logo.png" );
	
#line 99 "balsa-initdruid.c"
 }
}


#line 57 "balsa-initdruid.gob"
GtkObject *
balsa_initdruid_new (GtkWindow *window)
{
	g_return_val_if_fail (GTK_IS_WINDOW (window), (GtkObject *)0);
	g_return_val_if_fail (window != NULL, (GtkObject *)0);
	{
#line 57 "balsa-initdruid.gob"
		 
		GtkObject *self = GTK_OBJECT( GET_NEW );
		(BALSA_INITDRUID( self ))->window = GTK_WIDGET( window );
		gtk_object_ref( GTK_OBJECT( window ) );
		gtk_container_add( GTK_CONTAINER( (BALSA_INITDRUID( self ))->window ), GTK_WIDGET( self ) );
		return self;
	 
#line 119 "balsa-initdruid.c"
	}
}


#line 83 "balsa-initdruid.gob"
static void 
balsa_initdruid_cancel (GnomeDruid *_self)
#define PARENT_HANDLER(args...) \
	{ if(GNOME_DRUID_CLASS(parent_class)->cancel) \
		(* GNOME_DRUID_CLASS(parent_class)->cancel)(##args); }
{
	{
#line 84 "balsa-initdruid.gob"
		
		GtkWidget *dialog;

		dialog = gnome_question_dialog_modal( _("This will exit Balsa. Do you\n"
				        "really want to do this?"), 
				 	(GnomeReplyCallback) really_cb, _self );
    		gnome_dialog_run( GNOME_DIALOG( dialog ) );
	
#line 141 "balsa-initdruid.c"
	}
}
#undef PARENT_HANDLER

#line 93 "balsa-initdruid.gob"
void 
balsa_initdruid_finished (BalsaInitDruid *self)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (BALSA_IS_INITDRUID (self));
	{
#line 93 "balsa-initdruid.gob"
		
		gtk_object_destroy( GTK_OBJECT( self->welcome ) );
		gtk_object_destroy( GTK_OBJECT( self->user ) );
		gtk_object_destroy( GTK_OBJECT( self->std_boxes ) );
		gtk_object_destroy( GTK_OBJECT( self->finish ) );
		gtk_object_unref( GTK_OBJECT( self->window ) );
		gtk_object_destroy( GTK_OBJECT( self->window ) );
		gtk_object_destroy( GTK_OBJECT( self ) );
		gtk_main_quit();
	
#line 164 "balsa-initdruid.c"
	}
}
#undef GET_NEW


/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method, it pollutes the namespace but the call
  is weird enough.  I need to find a better way to do
  this */
void __balsa_initdruid_really_bad_hack_to_avoid_warnings(void);
void
__balsa_initdruid_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))new)();
	((void (*)(void))finished)();
}

